services: # Définir tous les services souhaités ci-dessous, par exemple dans ce cas, Grafana (un service est un conteneur)
  grafana:
    user: "1000:1000" # Configurer Grafana pour créer les dossiers en tant qu'utilisateur courant
    image: grafana/grafana:10.2.2 # Spécifier l'image Grafana disponible sur Docker Hub
    ports:
      - "3000:3000" # Le premier est le port local, le deuxième est le port du conteneur
    networks: # Définir un réseau pour le conteneur
      monprojetgrafana:
    volumes: # Mapper les volumes locaux avec ceux du conteneur (voir la documentation officielle pour plus de détails)
      # Commande recommandée : sudo chmod -R 777 data
      - ./data/grafana/lib:/var/lib/grafana
      - ./data/grafana/logs:/var/log/grafana
      - ./data/grafana/plugins:/var/lib/grafana/plugins

networks: # Créer un réseau interne pour connecter les différents services
  monprojetgrafana: # Nom du réseau

